FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip
RUN git clone https://github.com/hiyouga/LLaMA-Factory.git /opt/llama-factory
WORKDIR /opt/llama-factory
RUN pip install --no-cache-dir -e .
EXPOSE 7860
CMD ["llamafactory-cli", "webui"]